[build]
target = "thumbv7em-none-eabihf"

# Setup as recommended by probe-run. This needs to be adjusted for when running on different hardware.
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nRF52832_xxAA"
