stages:
  - build
  - test
  - deploy

build-stable:
  stage: build
  image: "rust:latest"
  script:
    - make build

build-nightly:
  stage: build
  image: "rustlang/rust:nightly"
  script:
    - make build

test-stable:
  stage: test
  image: "rust:latest"
  script:
    - make test

test-nightly:
  stage: test
  image: "rustlang/rust:nightly"
  script:
    - make test

pages:
  stage: deploy
  image: "rustlang/rust:nightly"
  script:
    - make doc
    - mv target/doc public
  artifacts:
    paths:
      - public
  only:
    - master

