[workspace]
members  = ["minicbor", "minicbor-derive", "minicbor-io", "minicbor-tests", "minicbor-tests-client"]
exclude  = ["minicbor-tests-nostd", "minicbor-tests-defmt"]
resolver = "2"

[profile.bench]
lto = true
codegen-units = 1
