[workspace]
members = [
    "minicbor",
    "minicbor-derive",
    "minicbor-io",
    "minicbor-tests",
    "minicbor-tests-nostd"
]

[profile.dev]
panic = "abort"

[profile.bench]
lto = true
codegen-units = 1
